### ISSUE TITLE
Project Management - CDR Presentation

### ISSUE THREAD

**Issue by anjali-hole** [Mackay-Fisher/MyHealthArc#31]

**Comment by anjali-hole** [comment]
Things to Have
- [x] Intro
- [x] Problem Statement
- [x] Solution
- [x] Features
- [x] Tech Stack
- [x] System Architecture
- [x] Details on how database/api requests are made
- [x] Demo showing how backend works
- [x] Demo for frontend
- [x] Measures of success
- [ ] Plans for testing/evaluation: include sample tests
- [x] Project status/management
- [x] future steps
- [x] problems faced
- [ ] potential upcoming problems/solutions
- [x] mention spending

**Comment by ShahirAliGit** [comment]
CDR finished 10/31
